In [6]:
#tast 1
import numpy as np
x = np.zeros(10)
x[4] = 5
x

array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

In [10]:
#Task 2
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [14]:
#Task 3
x = np.arange(0,10)
rev_x = np.flip(x)
rev_x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [15]:
#Task 4
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
#Task 5
x = [1,2,0,0,4,0]
x_nonzero = np.nonzero(x)
x_nonzero

(array([0, 1, 4]),)

In [38]:
#Task 6
x = np.random.rand(3,3,3)
x

array([[[0.90983107, 0.30534844, 0.54144267],
        [0.56237049, 0.85984248, 0.45257985],
        [0.36723118, 0.8116147 , 0.90254208]],

       [[0.99372224, 0.86309751, 0.76565427],
        [0.15881008, 0.8157127 , 0.17405437],
        [0.83849592, 0.17039807, 0.03240323]],

       [[0.32043602, 0.08784844, 0.54564978],
        [0.90475846, 0.0675066 , 0.39456599],
        [0.82294834, 0.2295724 , 0.71802084]]])

In [37]:
#Task 7
x = np.random.rand(10,10)
x_min = np.amin(x)
x_max = np.amax(x)
x, x_min, x_max

(array([[0.5141126 , 0.63107723, 0.57314969, 0.76543644, 0.47398622,
         0.31266097, 0.12106352, 0.36163209, 0.90331357, 0.44399297],
        [0.27301991, 0.30260367, 0.94820655, 0.75491652, 0.12835942,
         0.3671316 , 0.35471283, 0.92881735, 0.92220782, 0.27475439],
        [0.22123111, 0.73055168, 0.60771319, 0.5374005 , 0.9237535 ,
         0.77140763, 0.67669715, 0.64241579, 0.76180182, 0.40999365],
        [0.48748494, 0.59995445, 0.79069782, 0.55682391, 0.79007988,
         0.2580939 , 0.24241924, 0.33784763, 0.87573638, 0.723136  ],
        [0.12940972, 0.4731376 , 0.9006526 , 0.01026225, 0.88785146,
         0.84052157, 0.36864277, 0.56183585, 0.40179945, 0.69654552],
        [0.31203956, 0.22610365, 0.7123854 , 0.047699  , 0.86808604,
         0.24773079, 0.43545747, 0.13395285, 0.78479777, 0.09424527],
        [0.6942993 , 0.76918678, 0.16380216, 0.1715819 , 0.23775185,
         0.0973439 , 0.88518624, 0.19767599, 0.7708997 , 0.07912155],
        [0.48771197, 0.0091

In [33]:
#Task 8
x = np.ones((4,4))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])