In [4]:
import pandas as pd 
import numpy as np

In [5]:
#Series
#Creating series using a list

ps = pd.Series([1, 2, 3])
ps

0    1
1    2
2    3
dtype: int64

In [6]:
np.array([1, 2, 3])

array([1, 2, 3])

In [7]:
#Viewing series as an array
ps.values

array([1, 2, 3])

In [8]:
#labeling your series as per your own choice. you dont have this liberty in numpy
my_first_series = pd.Series([1, 2, 3], index = ['A', 'B', 'C'])
my_first_series

A    1
B    2
C    3
dtype: int64

In [9]:
my_first_series.index

Index(['A', 'B', 'C'], dtype='object')

In [10]:
#use index to access its value
my_first_series['A']

1

In [11]:
#manipulating the value of a series through an index
my_first_series['A'] = 100
my_first_series

A    100
B      2
C      3
dtype: int64

In [14]:
#Accessing subeset of series using indices
my_first_series[['A','C']]

A    100
C      3
dtype: int64

In [15]:
#filtering series using a condition
my_first_series[my_first_series > 5]

A    100
dtype: int64

In [16]:
my_first_series[my_first_series < 5]

B    2
C    3
dtype: int64

In [17]:
#Create a Series

my_first_series = pd.Series(np.arange(10))
my_first_series

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [18]:
#creating a series using a tuple
my_first_series = pd.Series((1, 2, 3, 4, 5, 6))
my_first_series

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [14]:
#creating a series using a dictionary. Keys are inferred as indices. 
my_first_series = pd.Series({'John' : 34, 'Jim' : 30, 'Sara' : 26, 'Anil' : 40, 'Majid' : 38})
my_first_series

John     34
Jim      30
Sara     26
Anil     40
Majid    38
dtype: int64

In [15]:
my_first_series.John

34

In [16]:
my_first_series['Majid']

38

In [49]:
#DataFrame
#Create a dataframe using a dictionary

data = {"Name" : ['Ohio', 'Ontario', 'London', 'Paris', 'Melbourne', 'Delhi', 'Beijing'],
        "year" : [2020, 2023, 2019, 2018, 2010, 1999, 1996],
        "cases" :[34, 12, 50, 30, 49, 190, 80]}
data

{'Name': ['Ohio',
  'Ontario',
  'London',
  'Paris',
  'Melbourne',
  'Delhi',
  'Beijing'],
 'year': [2020, 2023, 2019, 2018, 2010, 1999, 1996],
 'cases': [34, 12, 50, 30, 49, 190, 80]}

In [50]:
#A 2-d data structure labeled at both the dimensions. 
my_first_dataframe = pd.DataFrame(data, index = ['A', 'B', 'C', 'D', 'E', 'F', 'G'])
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
D      Paris  2018     30
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [19]:
#just see top 5 values
my_first_dataframe.head()

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
D      Paris  2018     30
E  Melbourne  2010     49

In [20]:
#just display bottom fove values
my_first_dataframe.tail()

Name  year  cases
C     London  2019     50
D      Paris  2018     30
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [21]:
#dataframe in a certain order
pd.DataFrame(data, columns = ['year', 'Name', 'cases'])

year       Name  cases
0  2020       Ohio     34
1  2023    Ontario     12
2  2019     London     50
3  2018      Paris     30
4  2010  Melbourne     49
5  1999      Delhi    190
6  1996    Beijing     80

In [22]:
#access a column
my_first_dataframe['Name']

A         Ohio
B      Ontario
C       London
D        Paris
E    Melbourne
F        Delhi
G      Beijing
Name: Name, dtype: object

In [23]:
#access a row by the name of the index
my_first_dataframe.loc['G']

Name     Beijing
year        1996
cases         80
Name: G, dtype: object

In [24]:
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
D      Paris  2018     30
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [25]:
#Accessing a particular element requires selecting a column and the index
my_first_dataframe['Name']['D']

'Paris'

In [26]:
#Replacing a particular value in dataframe
my_first_dataframe['Name']['D'] = 'Durham'
my_first_dataframe

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
D     Durham  2018     30
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [27]:
#Delete or drop a row or a column

my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
D     Durham  2018     30
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [28]:
#Lets say want to drop 4th index

my_first_dataframe.drop('D')

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [29]:
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
D     Durham  2018     30
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [51]:
#The drop method just temporarily drops and shows you a view of it. In actual its not dropped

my_first_dataframe.drop('D', inplace = True)

In [52]:
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [32]:
#what if you want to drop a column

my_first_dataframe.drop('year', axis = 1)

Name  cases
A       Ohio     34
B    Ontario     12
C     London     50
E  Melbourne     49
F      Delhi    190
G    Beijing     80

In [33]:
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [34]:
#Access via filtering over a condition on one column
my_first_dataframe[my_first_dataframe['cases'] < 50]

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
E  Melbourne  2010     49

In [35]:
my_first_dataframe[my_first_dataframe['year'] > 2015]

Name  year  cases
A     Ohio  2020     34
B  Ontario  2023     12
C   London  2019     50

In [36]:
#Accessing using multiple conditions
my_first_dataframe[((my_first_dataframe['year'] > 2015) & (my_first_dataframe['cases'] > 30))]

Name  year  cases
A    Ohio  2020     34
C  London  2019     50

In [37]:
#Sorting

my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [38]:
my_new_dataframe = my_first_dataframe.set_index('year')
my_new_dataframe

Name  cases
year                  
2020       Ohio     34
2023    Ontario     12
2019     London     50
2010  Melbourne     49
1999      Delhi    190
1996    Beijing     80

In [39]:
my_new_dataframe.sort_index(ascending=True)

Name  cases
year                  
1996    Beijing     80
1999      Delhi    190
2010  Melbourne     49
2019     London     50
2020       Ohio     34
2023    Ontario     12

In [40]:
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [41]:
#Sorting without setting an index
my_first_dataframe.sort_values('year')

Name  year  cases
G    Beijing  1996     80
F      Delhi  1999    190
E  Melbourne  2010     49
C     London  2019     50
A       Ohio  2020     34
B    Ontario  2023     12

In [42]:
my_first_dataframe.sort_values(['Name','year'])

Name  year  cases
G    Beijing  1996     80
F      Delhi  1999    190
C     London  2019     50
E  Melbourne  2010     49
A       Ohio  2020     34
B    Ontario  2023     12

In [43]:
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [45]:
my_first_dataframe[['cases']].sum()

cases    415
dtype: int64

In [46]:
my_first_dataframe[['cases']].mean()

cases    69.166667
dtype: float64

In [47]:
np.random.randint(5, size = (7))

array([0, 1, 1, 1, 2, 1, 0])

In [53]:
#Add a column to an existing dataframe
my_first_dataframe['group'] = np.random.randint(5, size = (6))
my_first_dataframe

Name  year  cases  group
A       Ohio  2020     34      0
B    Ontario  2023     12      1
C     London  2019     50      0
E  Melbourne  2010     49      2
F      Delhi  1999    190      2
G    Beijing  1996     80      4

In [54]:
#unique values in a column
my_first_dataframe['group'].unique()

array([0, 1, 2, 4])

In [55]:
#frequency of the column
my_first_dataframe['group'].value_counts()

2    2
0    2
4    1
1    1
Name: group, dtype: int64

Create a dataframe from a dictionary where the keys are the names of countries, the values are the gdp and indices are last 10 years. 
Now try to find the average gdp combined for all countries over past 10 years. 

In [27]:
data = {'India' : [3000,2900,2800,2700,2600,2500,2400,2300,2200,2100],
        'US' : [21000,20000,19000,18000,17000,16000,15000,14000,13500,12000],
        'UK' : [1500,1400,1300,1200,900,850,700,600,500,490],
        'China' : [15000,14000,13000,12500,12000,11500,11000,10500,10000,9500],
        'Japan' : [5000,4800,4600,4400,4200,4000,3800,3600,3400,3200],
        'Germany' : [4500,4300,3900,3600,3300,3000,2800,2600,2200,2000],
        'France' : [2850,2650,2450,2250,2050,2000,1950,1750,1650,1500],
        'Italy' : [2500,2300,2150,2000,1900,1800,1700,1600,1500,1450],
        'Canada' : [2000,1900,1800,1700,1600,1500,1400,1300,1200,1100],
        'South Korea' : [1900,1800,1700,1600,1500,1400,1300,1200,1100,1000]}
new_frame = pd.DataFrame(data, index = [2023,2022,2021,2020,2019,2018,2017,2016,2015,2014])
new_frame

India     US    UK  China  Japan  Germany  France  Italy  Canada  \
2023   3000  21000  1500  15000   5000     4500    2850   2500    2000   
2022   2900  20000  1400  14000   4800     4300    2650   2300    1900   
2021   2800  19000  1300  13000   4600     3900    2450   2150    1800   
2020   2700  18000  1200  12500   4400     3600    2250   2000    1700   
2019   2600  17000   900  12000   4200     3300    2050   1900    1600   
2018   2500  16000   850  11500   4000     3000    2000   1800    1500   
2017   2400  15000   700  11000   3800     2800    1950   1700    1400   
2016   2300  14000   600  10500   3600     2600    1750   1600    1300   
2015   2200  13500   500  10000   3400     2200    1650   1500    1200   
2014   2100  12000   490   9500   3200     2000    1500   1450    1100   

      South Korea  
2023         1900  
2022         1800  
2021         1700  
2020         1600  
2019         1500  
2018         1400  
2017         1300  
2016         1200  
2015         1100  
2014         1000

In [35]:
gdp_avg = sum([new_frame['India'],new_frame['US'],new_frame['UK'],new_frame['China'],new_frame['Japan'],new_frame['Germany'],new_frame['France'],new_frame['Italy'],new_frame['Canada'],new_frame['South Korea']])
gdp_avg = gdp_avg/10
gdp_avg


2023    5925.0
2022    5605.0
2021    5270.0
2020    4995.0
2019    4705.0
2018    4455.0
2017    4205.0
2016    3945.0
2015    3725.0
2014    3434.0
dtype: float64